micronaut:
  application:
    name: identity
  executors:
    io:
      type: fixed
      n-threads: 5
  security:
    authentication: bearer
    endpoints:
      login:
        path: /token
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_SIGNATURE_SECRET}
  server:
    context-path: /identity/api
    port: ${SERVER_PORT}
datasources:
  default:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_SECRET}
    schema-generate: NONE
    dialect: POSTGRES
    schema: ${DB_SCHEMA}
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: "br.pucminas.gisa.identity.application.domain"
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        hbm2ddl:
          auto: none
liquibase:
  datasources:
    default:
      change-log: "classpath:db/master-changelog.groovy"
      default-schema: ${DB_SCHEMA}
      liquibase-schema: liquibase
      enabled: true
jackson:
  bean-introspection-module: true
  property-naming-strategy: LOWER_CAMEL_CASE
  date-format: "yyyy-MM-dd'T'HH:mm:ss.SSSZ"
  time-zone: "America/Sao_Paulo"
  locale: pt_BR
  deserialization:
    failOnNumbersForEnums: true
    failOnUnknownProperties: true
  serialization:
    writeDatesAsTimestamps: false
    closeCloseable: true
    indentOutput: true
